# Generated by Django 6.1 on 2026-08-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Stock', models.PositiveIntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Last_Updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('GROCERY', 'Grocery'), ('CLOTHING', 'Clothing'), ('HOME', 'Home & Kitchen')], default='GROCERY', max_length=20)),
                ('unit', models.CharField(choices=[('PCS', 'Pieces (pcs)'), ('KG', 'Kilogram (kg)'), ('PACK', 'Pack'), ('LITRE', 'Litre (L)')], default='PCS', max_length=10)),
            ],
        ),
    ]
